import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import footer from '../styles/Footer.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gyaku-Hyotei</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.section}>
          <h1 className={styles.title}>Gyaku&nbsp;-&nbsp;Hyotei</h1>

          <p className={styles.description}>
            このページは Titech Info
            の姉妹ページです。ここに、説明を書きます。テスト、テスト、テスト
          </p>
        </div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={styles.border}>教養科目 &rarr;</h2>
            <p className={styles.back}>文系教養科目</p>
            <p className={styles.back}>英語科目</p>
            <p className={styles.back}>第二外国語科目</p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.border}>初年次専門科目 &rarr;</h2>
            <p className={styles.back}>理学院</p>
            <p className={styles.back}>工学院</p>
            <p className={styles.back}>物質理工学院</p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.border}>理学院 &rarr;</h2>
            <p className={styles.back}>数学系</p>
            <p className={styles.back}>物理学系</p>
            <p className={styles.back}>化学系</p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.border}>工学院 &rarr;</h2>
            <p></p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.border}>物質理工学院 &rarr;</h2>
            <p></p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.border}>情報理工学院 &rarr;</h2>
            <p></p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.border}>環境社会理工学院 &rarr;</h2>
            <p></p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.border}>生命理工学院 &rarr;</h2>
            <p></p>
          </div>
        </div>
      </main>

      <div className={footer.footer}>
        <div className={footer.contactus}>
          <a
            href="https://forms.gle/ZtJGJfxKadJ6VuAa8"
            target="_blank"
            rel="noreferrer"
            className={footer.contactusLink}
          >
            CONTACT US
          </a>
        </div>
        <div className={footer.copyright}>Copyright 2021 Titech Info</div>
      </div>
    </div>
  )
}
